language:
  - python

python:
  - "2.7"

install:
  - "pip install -r requirements.txt"

script:
  - export PYTHONPATH="."
  - py.test

notifications:
  email:
    on_success: never
    on_failure: always
